/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_chartstate_free: (a: number, b: number) => void;
export const chartstate_add_head: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const chartstate_add_indicator: (a: number, b: number, c: number) => any;
export const chartstate_add_tail: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const chartstate_backtest: (a: number, b: number, c: number, d: number, e: number) => any;
export const chartstate_backtest_named: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const chartstate_bar_count: (a: number) => number;
export const chartstate_clear_script: (a: number) => void;
export const chartstate_load_head: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => any;
export const chartstate_load_tail: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => any;
export const chartstate_new: (a: number, b: number) => number;
export const chartstate_raw_bar_count: (a: number) => number;
export const chartstate_remove_indicator: (a: number, b: number, c: number) => void;
export const chartstate_reset: (a: number) => void;
export const chartstate_reset_bars: (a: number) => void;
export const chartstate_set_candle_transform: (a: number, b: number, c: number, d: number) => any;
export const chartstate_set_indicators: (a: number, b: number, c: number) => any;
export const chartstate_set_script: (a: number, b: number, c: number) => any;
export const chartstate_snapshot: (a: number) => any;
export const chartstate_symbol: (a: number) => [number, number];
export const chartstate_update_indicator: (a: number, b: number, c: number, d: number, e: number) => any;
export const heikin_ashi: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => any;
export const indicator_catalog: () => any;
export const init: () => void;
export const list_indicators: () => any;
export const list_mtf_strategies: () => any;
export const list_strategies: () => any;
export const run_backtest: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number) => any;
export const run_indicators: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number) => any;
export const run_mtf_backtest: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => any;
export const run_mtf_script_backtest: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => any;
export const run_script_backtest: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => any;
export const smooth_ha: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => any;
export const validate_script: (a: number, b: number, c: number, d: number) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
