default:
    @just --list

fmt:
    gofmt -w $(rg --files cmd internal | rg '\.go$$')

test:
    mkdir -p ./tmp/gocache ./tmp/gotmp
    GOCACHE=$(pwd)/tmp/gocache GOTMPDIR=$(pwd)/tmp/gotmp go test ./...

run:
    mkdir -p ./tmp/gocache ./tmp/gotmp
    GOCACHE=$(pwd)/tmp/gocache GOTMPDIR=$(pwd)/tmp/gotmp go run ./cmd/orchestrator/

dev:
    ~/.go/bin/air
