package clid

import (
	"crypto/rand"
	"encoding/binary"
	"strconv"
	"strings"
	"time"
)

// Prefix marks a client order id (clOrdId) that mallow generated. The prefix
// lets every fill path decide statelessly whether an order is ours (route by clid)
// or external/bracket/manual (route by exchange id) — see CanonKey.
// Kept short and alphanumeric so the full id fits the tightest exchange limit
// (OKX clOrdId: ≤32 chars, [A-Za-z0-9]).
const Prefix = "mlw"

// New returns a fresh client order id: "mlw" + base36 nanos + base36
// random. ~18 chars, alphanumeric, unique within an account. Generated before the
// order is placed so it can be tracked ahead of the REST response.
func New() string {
	ts := strconv.FormatInt(time.Now().UnixNano(), 36)
	var b [4]byte
	_, _ = rand.Read(b[:])
	rnd := strconv.FormatUint(uint64(binary.BigEndian.Uint32(b[:])), 36)
	return Prefix + ts + rnd
}

// CanonKey returns the canonical routing/tracking key for an order.
// Orders we placed carry an "mlw"-prefixed client id that is known before the order
// reaches the exchange — so it is the race-free routing key. Everything else
// (bracket orders, manual orders, adapters that don't echo our clid) keys by the
// exchange-assigned id. The decision is purely string-based so every fill path
// (WS, REST poll, reconcile) derives the same key without consulting any map.
func CanonKey(clientOrderID, exchangeID string) string {
	if strings.HasPrefix(clientOrderID, Prefix) {
		return clientOrderID
	}
	return exchangeID
}

// IsOurClid reports whether a client order id was generated by mallow.
func IsOurClid(clientOrderID string) bool {
	return strings.HasPrefix(clientOrderID, Prefix)
}
