package handler

import (
	"encoding/json"
	"log/slog"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	nats "github.com/nats-io/nats.go"
	"github.com/redis/go-redis/v9"

	"mallow/identity/internal/middleware"
	authdto "mallow/identity/internal/module/auth/dto"
	"mallow/identity/internal/module/user/domain"
	userdto "mallow/identity/internal/module/user/dto"
	"mallow/identity/internal/module/user/service"
	"mallow/identity/internal/shared"
)

const (
	telegramOTPPrefix = "telegram:link:"

	// subjectTelegramLinked is the JetStream subject published after a successful link.
	subjectTelegramLinked = "user.telegram.linked"
	// subjectTelegramUnlinked is the JetStream subject published after a successful unlink.
	subjectTelegramUnlinked = "user.telegram.unlinked"
)

// telegramLinkEvent is the payload published to JetStream on telegram account link/unlink.
type telegramLinkEvent struct {
	EventID    string `json:"event_id"`
	Action     string `json:"action"` // linked | unlinked
	UserID     string `json:"user_id"`
	TelegramID string `json:"telegram_id"`
	OccurredAt string `json:"occurred_at"`
}

// telegramLinkPayload is what the bot stores in Redis keyed by OTP.
type telegramLinkPayload struct {
	ID       string `json:"id"`
	Username string `json:"username,omitempty"`
}

// TelegramHandler handles Telegram account linking endpoints.
type TelegramHandler struct {
	userService service.IUserService
	rdb         *redis.Client
	js          nats.JetStreamContext // may be nil if NATS is unavailable
	botUsername string
}

func NewTelegramHandler(userService service.IUserService, rdb *redis.Client, js nats.JetStreamContext, botUsername string) *TelegramHandler {
	return &TelegramHandler{
		userService: userService,
		rdb:         rdb,
		js:          js,
		botUsername: botUsername,
	}
}

func (h *TelegramHandler) RegisterRoutes(
	r *gin.Engine,
	authMiddle *middleware.Middleware,
	serviceSecret string,
) {
	// Public: bot info for frontend "Connect Telegram" button
	r.GET("/api/v1/auth/telegram/bot", h.botInfo)

	auth := r.Group("/api/v1/auth/telegram", authMiddle.AuthMiddleware())
	auth.POST("/confirm-link", h.confirmLink)
	auth.DELETE("/link", h.unlink)

	// Internal: strategist resolves telegram_id → user
	internal := r.Group("/api/v1/internal/telegram", middleware.ServiceAuth(serviceSecret))
	internal.GET("/user/:telegram_id", h.getUserByTelegram)
}

// BotInfo godoc
// @Summary Get Telegram bot connection info
// @Description Returns the bot username and deep link for the frontend "Connect Telegram" button
// @Tags auth
// @Produce json
// @Success 200 {object} authdto.TelegramBotInfoResponse
// @Router /api/v1/auth/telegram/bot [get]
func (h *TelegramHandler) botInfo(c *gin.Context) {
	username := h.botUsername
	link := ""
	if username != "" {
		// ?start=link tells Telegram to auto-send "/start link" when user opens the bot,
		// so the bot immediately generates an OTP without the user typing /link manually.
		link = "https://t.me/" + username + "?start=link"
	}
	shared.RespondWithSuccess(c, http.StatusOK, "ok", authdto.TelegramBotInfoResponse{
		BotUsername: username,
		Link:        link,
	})
}

// ConfirmTelegramLink godoc
// @Summary Confirm Telegram account linking
// @Description Confirm Telegram account linking with OTP generated by the identity Telegram bot
// @Tags auth
// @Accept json
// @Produce json
// @Security BearerAuth
// @Param request body authdto.ConfirmTelegramLinkRequest true "Telegram OTP payload"
// @Success 200 {object} shared.Success
// @Failure 400 {object} shared.ErrorResponse
// @Failure 401 {object} shared.ErrorResponse
// @Failure 409 {object} shared.ErrorResponse
// @Failure 500 {object} shared.ErrorResponse
// @Router /api/v1/auth/telegram/confirm-link [post]
func (h *TelegramHandler) confirmLink(c *gin.Context) {
	var req authdto.ConfirmTelegramLinkRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		shared.RespondWithError(c, http.StatusBadRequest, "invalid request data")
		return
	}

	currentUser, ok := middleware.GetCurrentUser(c)
	if !ok {
		shared.RespondWithError(c, http.StatusUnauthorized, "user not found in context")
		return
	}
	userID := currentUser.ID.String()

	// Look up payload from OTP (bot stores JSON: {"id":"...","username":"..."})
	key := telegramOTPPrefix + req.OTP
	raw, err := h.rdb.GetDel(c.Request.Context(), key).Result()
	if err != nil {
		shared.RespondWithError(c, http.StatusBadRequest, "invalid or expired OTP")
		return
	}

	var payload telegramLinkPayload
	if err := json.Unmarshal([]byte(raw), &payload); err != nil {
		shared.RespondWithError(c, http.StatusBadRequest, "invalid OTP payload")
		return
	}
	telegramID := payload.ID

	// Check telegram_id not already linked to another user.
	existing, err := h.userService.GetByLinkedAccount(c.Request.Context(), "telegram", telegramID)
	if err == nil && existing.ID.String() != userID {
		shared.RespondWithError(c, http.StatusConflict, "telegram account already linked to another user")
		return
	}

	username := payload.Username
	if username != "" && username[0] != '@' {
		username = "@" + username
	}

	account := domain.LinkedAccount{
		Provider:   "telegram",
		ProviderID: telegramID,
		Username:   username,
	}
	if err := h.userService.LinkAccount(c.Request.Context(), userID, account); err != nil {
		shared.RespondWithAppError(c, shared.ErrInternal.WithError(err))
		return
	}

	h.publishTelegramEvent(subjectTelegramLinked, "linked", userID, telegramID)

	shared.RespondWithSuccessNoData(c, http.StatusOK, "telegram account linked successfully")
}

// UnlinkTelegram godoc
// @Summary Unlink Telegram account
// @Description Unlink Telegram account from current authenticated user
// @Tags auth
// @Accept json
// @Produce json
// @Security BearerAuth
// @Param request body authdto.UnlinkTelegramRequest true "Telegram unlink payload"
// @Success 200 {object} shared.Success
// @Failure 400 {object} shared.ErrorResponse
// @Failure 401 {object} shared.ErrorResponse
// @Failure 500 {object} shared.ErrorResponse
// @Router /api/v1/auth/telegram/link [delete]
func (h *TelegramHandler) unlink(c *gin.Context) {
	var req authdto.UnlinkTelegramRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		shared.RespondWithError(c, http.StatusBadRequest, "invalid request data")
		return
	}

	currentUser, ok := middleware.GetCurrentUser(c)
	if !ok {
		shared.RespondWithError(c, http.StatusUnauthorized, "user not found in context")
		return
	}

	if err := h.userService.UnlinkAccount(c.Request.Context(), currentUser.ID.String(), "telegram", req.ProviderID); err != nil {
		shared.RespondWithAppError(c, shared.ErrInternal.WithError(err))
		return
	}

	h.publishTelegramEvent(subjectTelegramUnlinked, "unlinked", currentUser.ID.String(), req.ProviderID)

	shared.RespondWithSuccessNoData(c, http.StatusOK, "telegram account unlinked successfully")
}

// publishTelegramEvent fires a fire-and-forget JetStream message for telegram account lifecycle changes.
func (h *TelegramHandler) publishTelegramEvent(subject, action, userID, telegramID string) {
	if h.js == nil {
		return
	}
	payload, err := json.Marshal(telegramLinkEvent{
		EventID:    uuid.NewString(),
		Action:     action,
		UserID:     userID,
		TelegramID: telegramID,
		OccurredAt: time.Now().UTC().Format(time.RFC3339Nano),
	})
	if err != nil {
		slog.Error("telegram: marshal event", "subject", subject, "err", err)
		return
	}
	if _, err := h.js.Publish(subject, payload); err != nil {
		slog.Error("telegram: publish event", "subject", subject, "err", err)
	}
}

// GetUserByTelegram godoc
// @Summary Resolve user by Telegram ID (internal)
// @Description Internal service endpoint to resolve platform user by telegram_id
// @Tags internal
// @Produce json
// @Param telegram_id path string true "Telegram ID"
// @Success 200 {object} authdto.TelegramUserLookupResponse
// @Failure 404 {object} shared.ErrorResponse
// @Failure 500 {object} shared.ErrorResponse
// @Router /api/v1/internal/telegram/user/{telegram_id} [get]
func (h *TelegramHandler) getUserByTelegram(c *gin.Context) {
	telegramID := c.Param("telegram_id")
	user, err := h.userService.GetByLinkedAccount(c.Request.Context(), "telegram", telegramID)
	if err != nil {
		if err == shared.ErrUserNotFound {
			shared.RespondWithError(c, http.StatusNotFound, "user not found")
			return
		}
		shared.RespondWithAppError(c, shared.ErrInternal.WithError(err))
		return
	}
	acc := user.GetLinkedAccount("telegram")
	var telegramResp *userdto.LinkedAccountResponse
	if acc != nil {
		telegramResp = &userdto.LinkedAccountResponse{
			Provider:   acc.Provider,
			ProviderID: acc.ProviderID,
			Username:   acc.Username,
			LinkedAt:   acc.LinkedAt,
		}
	}

	shared.RespondWithSuccess(c, http.StatusOK, "user resolved by telegram successfully", authdto.TelegramUserLookupResponse{
		ID:       user.ID.String(),
		Email:    user.Email,
		FullName: user.FullName,
		Telegram: telegramResp,
	})
}
