-- Herald database schema.
-- Source of truth for dev: docker volume reset + docker compose up recreates from here.
-- Production uses migrate.rs which runs the same DDL on every startup (idempotent).
--
-- Two conceptual groups:
--   1. Strategy store   — strategies, watch_entries
--   2. Symbol registry  — providers, symbols, symbol_frames, crawl_state (shared with hist-data)
--
-- Timestamps are BIGINT Unix-ms (Rust chrono convention), not TIMESTAMPTZ.
-- IDs are TEXT (ULIDs generated by Rust ulid crate).

-- ── Strategy store ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS strategies (
    id          UUID    PRIMARY KEY,
    spec_hash   TEXT,                                   -- SHA-256 of canonical spec; NULL = legacy
    name        TEXT    NOT NULL,
    version     INT     NOT NULL DEFAULT 1,
    previous_id UUID    REFERENCES strategies(id),      -- parent pointer (lineage only)
    label       TEXT    NOT NULL,
    spec        JSONB   NOT NULL,                       -- full Rhai StrategySpec
    notes       TEXT,
    user_id     TEXT,                                   -- owner (JWT sub); NULL = system / backtest-created
    created_at  BIGINT  NOT NULL,
    UNIQUE (name, version),
    UNIQUE (spec_hash, user_id)
);
-- kind column intentionally absent: always 'rhai', no information content.

CREATE TABLE IF NOT EXISTS watch_entries (
    id           UUID    PRIMARY KEY,
    symbols      JSONB   NOT NULL,
    timeframe    TEXT,
    spec         JSONB   NOT NULL,
    webhook_url  TEXT,
    nats_subject TEXT,
    user_id      TEXT,                                   -- owner (JWT sub); NULL = system-created
    created_at   BIGINT  NOT NULL
);
-- exit_config intentionally absent: exit logic lives in the Rhai script spec.

CREATE INDEX IF NOT EXISTS idx_strategies_name_version  ON strategies(name, version DESC);

CREATE INDEX IF NOT EXISTS idx_watch_created            ON watch_entries(created_at DESC);

-- ── Symbol registry (shared by herald + hist-data) ────────────────────────────

CREATE TABLE IF NOT EXISTS providers (
    id         UUID    PRIMARY KEY,
    slug       TEXT    NOT NULL UNIQUE,  -- 'binance' | 'okx' | 'alpaca' | 'massive' | 'twelvedata' | 'vci'
    name       TEXT    NOT NULL,
    kind       TEXT    NOT NULL CHECK (kind IN ('exchange', 'data_provider')),
    created_at BIGINT  NOT NULL
);

CREATE TABLE IF NOT EXISTS symbols (
    id            UUID    PRIMARY KEY,
    provider_id   UUID    NOT NULL REFERENCES providers(id) ON DELETE RESTRICT,
    symbol        TEXT    NOT NULL,
    asset_class   TEXT    NOT NULL DEFAULT 'crypto'
                  CHECK (asset_class IN ('crypto', 'stock', 'forex')),
    live_enabled  BOOL    NOT NULL DEFAULT true,   -- herald WebSocket ingestion
    crawl_enabled BOOL    NOT NULL DEFAULT true,   -- hist-data historical crawl
    created_at    BIGINT  NOT NULL,
    UNIQUE (provider_id, symbol)
);

CREATE TABLE IF NOT EXISTS symbol_frames (
    id             UUID     PRIMARY KEY,
    symbol_id      UUID     NOT NULL REFERENCES symbols(id) ON DELETE CASCADE,
    frame          TEXT     NOT NULL,  -- 'M1' | 'M5' | 'H1' | 'H4' | 'D1' | 'W1'
    backfill_years INT      NOT NULL DEFAULT 0,   -- 0 = full history
    sink_frames    TEXT[]   NOT NULL DEFAULT '{}',
    UNIQUE (symbol_id, frame)
);

CREATE TABLE IF NOT EXISTS crawl_state (
    symbol_id       UUID    NOT NULL REFERENCES symbols(id) ON DELETE CASCADE,
    frame           TEXT    NOT NULL,
    last_success_at BIGINT,
    updated_at      BIGINT  NOT NULL,
    PRIMARY KEY (symbol_id, frame)
);

CREATE INDEX IF NOT EXISTS idx_symbols_provider    ON symbols(provider_id);
CREATE INDEX IF NOT EXISTS idx_symbol_frames_sym   ON symbol_frames(symbol_id);
CREATE INDEX IF NOT EXISTS idx_crawl_state_sym     ON crawl_state(symbol_id);

-- ── Seed providers ────────────────────────────────────────────────────────────

INSERT INTO providers (id, slug, name, kind, created_at) VALUES
    ('01000000-0000-7000-8000-000000000001', 'binance',    'Binance',     'exchange',      0),
    ('01000000-0000-7000-8000-000000000002', 'okx',        'OKX',         'exchange',      0),
    ('01000000-0000-7000-8000-000000000003', 'alpaca',     'Alpaca',      'exchange',      0),
    ('01000000-0000-7000-8000-000000000004', 'massive',    'Polygon.io',  'data_provider', 0),
    ('01000000-0000-7000-8000-000000000005', 'twelvedata', 'TwelveData',  'data_provider', 0),
    ('01000000-0000-7000-8000-000000000006', 'vci',        'Vietcap',     'data_provider', 0)
ON CONFLICT (slug) DO NOTHING;

-- ── Seed Binance symbols ──────────────────────────────────────────────────────

INSERT INTO symbols (id, provider_id, symbol, asset_class, live_enabled, crawl_enabled, created_at)
SELECT
    ('01000000-0000-7001-8000-' || LPAD(ROW_NUMBER() OVER ()::TEXT, 12, '0'))::UUID,
    '01000000-0000-7000-8000-000000000001'::UUID,
    sym, 'crypto', true, true, 0
FROM UNNEST(ARRAY[
    'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT',
    'ADAUSDT','AVAXUSDT','DOTUSDT','LINKUSDT','MATICUSDT'
]) AS sym
ON CONFLICT (provider_id, symbol) DO NOTHING;

INSERT INTO symbol_frames (id, symbol_id, frame, backfill_years, sink_frames)
SELECT
    ('01000000-0000-7011-8000-' || LPAD((ROW_NUMBER() OVER () * 2 - 1)::TEXT, 12, '0'))::UUID,
    s.id, 'M1', 0, ARRAY['M1','M5','M15','M30','H1','H4']
FROM symbols s JOIN providers p ON p.id = s.provider_id WHERE p.slug = 'binance'
ON CONFLICT (symbol_id, frame) DO NOTHING;

INSERT INTO symbol_frames (id, symbol_id, frame, backfill_years, sink_frames)
SELECT
    ('01000000-0000-7011-8000-' || LPAD((ROW_NUMBER() OVER () * 2)::TEXT, 12, '0'))::UUID,
    s.id, 'D1', 0, ARRAY['D1']
FROM symbols s JOIN providers p ON p.id = s.provider_id WHERE p.slug = 'binance'
ON CONFLICT (symbol_id, frame) DO NOTHING;

-- ── Seed OKX symbols ─────────────────────────────────────────────────────────

INSERT INTO symbols (id, provider_id, symbol, asset_class, live_enabled, crawl_enabled, created_at)
SELECT
    ('01000000-0000-7002-8000-' || LPAD(ROW_NUMBER() OVER ()::TEXT, 12, '0'))::UUID,
    '01000000-0000-7000-8000-000000000002'::UUID,
    sym, 'crypto', true, true, 0
FROM UNNEST(ARRAY[
    'BTC-USDT','ETH-USDT','BNB-USDT','SOL-USDT','XRP-USDT',
    'ADA-USDT','AVAX-USDT','DOT-USDT','LINK-USDT','POL-USDT'
]) AS sym
ON CONFLICT (provider_id, symbol) DO NOTHING;

INSERT INTO symbol_frames (id, symbol_id, frame, backfill_years, sink_frames)
SELECT
    ('01000000-0000-7012-8000-' || LPAD((ROW_NUMBER() OVER () * 2 - 1)::TEXT, 12, '0'))::UUID,
    s.id, 'M1', 0, ARRAY['M1','M5','M15','M30','H1','H4']
FROM symbols s JOIN providers p ON p.id = s.provider_id WHERE p.slug = 'okx'
ON CONFLICT (symbol_id, frame) DO NOTHING;

INSERT INTO symbol_frames (id, symbol_id, frame, backfill_years, sink_frames)
SELECT
    ('01000000-0000-7012-8000-' || LPAD((ROW_NUMBER() OVER () * 2)::TEXT, 12, '0'))::UUID,
    s.id, 'D1', 0, ARRAY['D1']
FROM symbols s JOIN providers p ON p.id = s.provider_id WHERE p.slug = 'okx'
ON CONFLICT (symbol_id, frame) DO NOTHING;
