// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hands": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "List hands",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by helm ID",
                        "name": "helm_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by account ID",
                        "name": "account_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_hand_domain_HandSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Create hand",
                "parameters": [
                    {
                        "description": "Hand create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.CreateHandReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_domain_HandSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Get hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_domain_HandSummary"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Update hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Hand update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.UpdateHandReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_domain_HandSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Delete hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/kill": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Kill hand — stop and flatten all positions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Pause hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/release": {
            "post": {
                "description": "Stop the hand without closing positions. Open legs are marked orphaned in the poslog; the hand will not reclaim them on restart.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Release a hand (orphan open positions)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/restart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Restart hand — stop then start (re-registers with signal herald)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/resume": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Resume hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Start hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hands/{id}/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hands"
                ],
                "summary": "Stop hand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "List helms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_HelmResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Get helm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_HelmDetailResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Update orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Orchestrator update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.UpdateHelmReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_HelmResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Disable helm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Enable helm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/exchange/account": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange"
                ],
                "summary": "Get live exchange account snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangeAccountResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/exchange/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange"
                ],
                "summary": "Get order status from the exchange",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Order ID (format: SYMBOL:numeric_id for Binance)",
                        "name": "order_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangeOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange"
                ],
                "summary": "Place a spot order directly on the exchange",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Order request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PlaceExchangeOrderReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangeOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange"
                ],
                "summary": "Cancel an open order on the exchange",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Order ID (format: SYMBOL:numeric_id for Binance)",
                        "name": "order_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/exchange/price": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange"
                ],
                "summary": "Get live price for a symbol",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Symbol (e.g. BTCUSDT)",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangePriceResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/halt/reset": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Reset orchestrator halt flag and restore to active",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/kill": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Kill orchestrator — flatten all hand positions and halt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "List orchestrator orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_OrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Pause orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/portfolio": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Get helm portfolio summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_PortfolioResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/positions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "List orchestrator positions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_PositionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/resume": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "Resume orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/helms/{id}/trades": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helms"
                ],
                "summary": "List orchestrator trades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_TradeResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mallow_helm_internal_shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mallow_helm_internal_module_hand_domain.ExitConfig": {
            "type": "object",
            "properties": {
                "max_bars": {
                    "description": "time-stop: close after N bars",
                    "type": "integer"
                },
                "sl": {
                    "description": "stop-loss",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.ExitLevel"
                        }
                    ]
                },
                "tp": {
                    "description": "take-profit",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.ExitLevel"
                        }
                    ]
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.ExitLevel": {
            "type": "object",
            "properties": {
                "expr": {
                    "description": "non-nil when ATR expression",
                    "type": "string"
                },
                "pct": {
                    "description": "non-nil when fixed fraction",
                    "type": "number"
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.HandHealthView": {
            "type": "object",
            "properties": {
                "last_error": {
                    "type": "string"
                },
                "last_error_at": {
                    "type": "string"
                },
                "last_order_at": {
                    "type": "string"
                },
                "last_signal_at": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.HandMetricsView": {
            "type": "object",
            "properties": {
                "loss_count": {
                    "type": "integer"
                },
                "orders_failed": {
                    "type": "integer"
                },
                "orders_filled": {
                    "type": "integer"
                },
                "orders_placed": {
                    "type": "integer"
                },
                "signals_filtered": {
                    "type": "integer"
                },
                "signals_received": {
                    "type": "integer"
                },
                "total_pnl": {
                    "type": "number"
                },
                "trades_approved": {
                    "type": "integer"
                },
                "win_count": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.HandRiskConfig": {
            "type": "object",
            "properties": {
                "exit": {
                    "description": "Exit rules — mirrors almanac's ExitConfig for backtest/live parity.\nsl/tp: fixed fraction (0.05) or ATR expression (\"2*atr\", \"1.5*atr(21)\").",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.ExitConfig"
                        }
                    ]
                },
                "trailing_stop_pct": {
                    "description": "TrailingStopPct is live-only (not in backtest ExitConfig).",
                    "type": "number"
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.HandSummary": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "health": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandHealthView"
                },
                "helm_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "market": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.MarketType"
                },
                "metrics": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandMetricsView"
                },
                "name": {
                    "type": "string"
                },
                "order_count": {
                    "type": "integer"
                },
                "position": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.PositionConfig"
                },
                "risk": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandRiskConfig"
                },
                "running": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "strategy": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.StrategySpec"
                },
                "symbols": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandType"
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.HandType": {
            "type": "string",
            "enum": [
                "signal_follower",
                "manual",
                "dca",
                "grid"
            ],
            "x-enum-varnames": [
                "HandTypeSignalFollower",
                "HandTypeManual",
                "HandTypeDCA",
                "HandTypeGrid"
            ]
        },
        "mallow_helm_internal_module_hand_domain.MarketType": {
            "type": "string",
            "enum": [
                "spot",
                "futures"
            ],
            "x-enum-varnames": [
                "MarketTypeSpot",
                "MarketTypeFutures"
            ]
        },
        "mallow_helm_internal_module_hand_domain.PositionConfig": {
            "type": "object",
            "properties": {
                "allocated_capital": {
                    "description": "Capital slice for this hand.\nAllocatedCapital (fixed USDT) takes priority over AllocatedPct.",
                    "type": "number"
                },
                "allocated_pct": {
                    "description": "0.20 = 20%",
                    "type": "number"
                },
                "fixed_qty": {
                    "description": "Fixed qty mode — overrides USD/pct sizing.",
                    "type": "number"
                },
                "max_position_pct": {
                    "description": "legacy fallback",
                    "type": "number"
                },
                "max_units": {
                    "description": "MaxUnits is the maximum number of concurrent entry legs.\n1 = no scaling (default). Each new entry signal while at max is rejected.\nOverridden downward by helm-level RiskConfig.MaxUnitsPerHand if set.",
                    "type": "integer"
                },
                "pyramid": {
                    "description": "Pyramid controls how additional entry signals are handled while a position is open.\ntrue  → merge into the existing leg: qty accumulates, avg_entry recalculated,\n        SL/TP replaced with values from the latest signal.\nfalse → open a new independent leg with its own SL/TP (up to MaxUnits).",
                    "type": "boolean"
                },
                "risk_per_trade_pct": {
                    "description": "for volatility mode",
                    "type": "number"
                },
                "size_mode": {
                    "description": "Sizing algorithm.",
                    "type": "string"
                },
                "unit_capital": {
                    "description": "Per-trade unit.\nUnitCapital (fixed USDT) takes priority over UnitPct.",
                    "type": "number"
                },
                "unit_pct": {
                    "description": "0.10 = 10% of allocated",
                    "type": "number"
                }
            }
        },
        "mallow_helm_internal_module_hand_domain.StrategySpec": {
            "type": "object",
            "properties": {
                "candle_type": {
                    "description": "CandleType controls the bar transform applied before indicators:\n  \"\"              / \"raw\"         — standard OHLCV (default)\n  \"heiken_ashi\"   / \"ha\"          — Heikin Ashi\n  \"smooth_ha\"                     — EMA-smoothed Heikin Ashi (see SmoothPeriod)",
                    "type": "string"
                },
                "min_strength": {
                    "description": "Signal strength filter [0–1]",
                    "type": "number"
                },
                "script": {
                    "description": "Rhai script — full Rhai source code (required)",
                    "type": "string"
                },
                "smooth_period": {
                    "description": "SmoothPeriod is the EMA period for \"smooth_ha\" mode (default 3, min 2).\nIgnored for other candle types.",
                    "type": "integer"
                },
                "timeframe": {
                    "description": "Timeframe the script operates on (e.g. \"M1\", \"M5\", \"H1\", \"D1\").\nDefaults to \"M1\" via HandConfig.Defaults().",
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.CreateHandReq": {
            "type": "object",
            "required": [
                "name",
                "strategy",
                "symbols"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "futures": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.FuturesDTO"
                },
                "helm_id": {
                    "type": "string"
                },
                "market": {
                    "enum": [
                        "spot",
                        "futures"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.MarketType"
                        }
                    ]
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "position": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.PositionDTO"
                },
                "risk": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.HandRiskConfigDTO"
                },
                "strategy": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.StrategyDTO"
                },
                "symbols": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "enum": [
                        "signal_follower",
                        "manual",
                        "dca",
                        "grid"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandType"
                        }
                    ]
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.FuturesDTO": {
            "type": "object",
            "properties": {
                "leverage": {
                    "type": "integer",
                    "maximum": 125,
                    "minimum": 1
                },
                "margin_type": {
                    "type": "string",
                    "enum": [
                        "isolated",
                        "cross"
                    ]
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.HandActionResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.HandRiskConfigDTO": {
            "type": "object",
            "properties": {
                "exit": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.ExitConfig"
                },
                "trailing_stop_pct": {
                    "type": "number",
                    "maximum": 1
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.PositionDTO": {
            "type": "object",
            "properties": {
                "allocated_capital": {
                    "type": "number",
                    "minimum": 0
                },
                "allocated_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "fixed_qty": {
                    "type": "number"
                },
                "max_position_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "max_units": {
                    "type": "integer",
                    "minimum": 1
                },
                "pyramid": {
                    "type": "boolean"
                },
                "risk_per_trade_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "size_mode": {
                    "type": "string",
                    "enum": [
                        "fixed_fractional",
                        "fixed_qty",
                        "percent_equity",
                        "volatility"
                    ]
                },
                "unit_capital": {
                    "type": "number",
                    "minimum": 0
                },
                "unit_pct": {
                    "type": "number",
                    "maximum": 1
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.StrategyDTO": {
            "type": "object",
            "properties": {
                "candle_type": {
                    "description": "CandleType controls the bar transform applied before indicators:\n  \"\"              / \"raw\"         — standard OHLCV (default)\n  \"heiken_ashi\"   / \"ha\"          — Heikin Ashi\n  \"smooth_ha\"                     — EMA-smoothed Heikin Ashi (see SmoothPeriod)",
                    "type": "string"
                },
                "min_strength": {
                    "description": "Signal strength filter [0–1]",
                    "type": "number"
                },
                "script": {
                    "description": "Rhai script — full Rhai source code (required)",
                    "type": "string"
                },
                "smooth_period": {
                    "description": "SmoothPeriod is the EMA period for \"smooth_ha\" mode (default 3, min 2).\nIgnored for other candle types.",
                    "type": "integer"
                },
                "timeframe": {
                    "description": "Timeframe the script operates on (e.g. \"M1\", \"M5\", \"H1\", \"D1\").\nDefaults to \"M1\" via HandConfig.Defaults().",
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_hand_dto.UpdateHandReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "position": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.PositionDTO"
                },
                "risk": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.HandRiskConfigDTO"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.ActionResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.ExchangeAccountResp": {
            "type": "object",
            "properties": {
                "cash": {
                    "type": "number"
                },
                "equity": {
                    "type": "number"
                },
                "positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ExchangePositionResp"
                    }
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.ExchangeConfigResp": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "broker_type": {
                    "type": "string"
                },
                "demo": {
                    "type": "boolean"
                },
                "testnet": {
                    "type": "boolean"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.ExchangeOrderResp": {
            "type": "object",
            "properties": {
                "filled_avg_price": {
                    "type": "number"
                },
                "filled_qty": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "qty": {
                    "type": "number"
                },
                "side": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.ExchangePositionResp": {
            "type": "object",
            "properties": {
                "avg_price": {
                    "type": "number"
                },
                "cur_price": {
                    "type": "number"
                },
                "qty": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.ExchangePriceResp": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.HelmDetailResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "capital": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "exchange": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ExchangeConfigResp"
                },
                "hands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandSummary"
                    }
                },
                "id": {
                    "type": "string"
                },
                "last_sync_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paused": {
                    "type": "boolean"
                },
                "portfolio": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PortfolioConfigDTO"
                },
                "risk": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.RiskConfigDTO"
                },
                "running": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.HelmResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "capital": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "exchange": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ExchangeConfigResp"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "portfolio": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PortfolioConfigDTO"
                },
                "risk": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.RiskConfigDTO"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.OrderResp": {
            "type": "object",
            "properties": {
                "filled_avg_price": {
                    "type": "number"
                },
                "filled_qty": {
                    "type": "number"
                },
                "hand_id": {
                    "type": "string"
                },
                "helm_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "qty": {
                    "type": "number"
                },
                "side": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.PlaceExchangeOrderReq": {
            "type": "object",
            "required": [
                "qty",
                "side",
                "symbol",
                "type"
            ],
            "properties": {
                "price": {
                    "type": "number"
                },
                "qty": {
                    "type": "number"
                },
                "side": {
                    "type": "string",
                    "enum": [
                        "buy",
                        "sell"
                    ]
                },
                "symbol": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "market",
                        "limit"
                    ]
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.PortfolioConfigDTO": {
            "type": "object",
            "properties": {
                "max_position_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "max_positions": {
                    "type": "integer",
                    "minimum": 1
                },
                "reserve_ratio": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.PortfolioResp": {
            "type": "object",
            "properties": {
                "cash": {
                    "type": "number"
                },
                "current_drawdown_pct": {
                    "type": "number"
                },
                "daily_pnl": {
                    "type": "number"
                },
                "equity": {
                    "type": "number"
                },
                "initial_capital": {
                    "type": "number"
                },
                "max_drawdown_pct": {
                    "type": "number"
                },
                "open_positions": {
                    "type": "integer"
                },
                "positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PositionResp"
                    }
                },
                "total_return_pct": {
                    "type": "number"
                },
                "total_trades": {
                    "type": "integer"
                },
                "win_rate_pct": {
                    "type": "number"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.PositionResp": {
            "type": "object",
            "properties": {
                "avg_price": {
                    "type": "number"
                },
                "current_price": {
                    "type": "number"
                },
                "entry_time": {
                    "type": "string"
                },
                "market_value": {
                    "type": "number"
                },
                "qty": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "unrealized_pnl": {
                    "type": "number"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.RiskConfigDTO": {
            "type": "object",
            "properties": {
                "daily_loss_limit_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "max_drawdown_pct": {
                    "type": "number",
                    "maximum": 1
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.TradeResp": {
            "type": "object",
            "properties": {
                "entry_price": {
                    "type": "number"
                },
                "entry_time": {
                    "type": "string"
                },
                "exit_price": {
                    "type": "number"
                },
                "exit_time": {
                    "type": "string"
                },
                "pnl": {
                    "type": "number"
                },
                "pnl_pct": {
                    "type": "number"
                },
                "qty": {
                    "type": "number"
                },
                "side": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "mallow_helm_internal_module_helm_dto.UpdateHelmReq": {
            "type": "object",
            "properties": {
                "capital": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "portfolio": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PortfolioConfigDTO"
                },
                "risk": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.RiskConfigDTO"
                }
            }
        },
        "mallow_helm_internal_shared.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_hand_domain_HandSummary": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandSummary"
                    }
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_HelmResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.HelmResp"
                    }
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_OrderResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.OrderResp"
                    }
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_PositionResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PositionResp"
                    }
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-array_mallow_helm_internal_module_helm_dto_TradeResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.TradeResp"
                    }
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_domain_HandSummary": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_domain.HandSummary"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_hand_dto_HandActionResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_hand_dto.HandActionResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ActionResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ActionResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangeAccountResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ExchangeAccountResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangeOrderResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ExchangeOrderResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_ExchangePriceResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.ExchangePriceResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_HelmDetailResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.HelmDetailResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_HelmResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.HelmResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "mallow_helm_internal_shared.SuccessResponse-mallow_helm_internal_module_helm_dto_PortfolioResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/mallow_helm_internal_module_helm_dto.PortfolioResp"
                },
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Helm Service API",
	Description:      "Helm service APIs for helms, hands, and signal engine control.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
