// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/backtest": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Runs a named strategy backtest via the Rust engine over NATS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backtest"
                ],
                "summary": "Run a backtest (named strategy)",
                "parameters": [
                    {
                        "description": "Backtest parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.BacktestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BacktestReport"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "504": {
                        "description": "engine unavailable (NATS timeout)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/backtest/cel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Runs a backtest using custom entry/exit CEL expressions. See /backtesting/docs/cel-strategy.md for variable reference.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backtest"
                ],
                "summary": "Run a CEL expression backtest",
                "parameters": [
                    {
                        "description": "CEL backtest parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CelBacktestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BacktestReport"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "504": {
                        "description": "engine unavailable (NATS timeout)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a message to the ADK-powered trading assistant and waits for a full reply.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Strategist"
                ],
                "summary": "Chat with AI strategist (sync)",
                "parameters": [
                    {
                        "description": "User message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "strategist unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/chat/stream": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Same as /api/chat but streams the reply as Server-Sent Events. Each ` + "`" + `data:` + "`" + ` line is a partial token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "AI Strategist"
                ],
                "summary": "Chat with AI strategist (SSE stream)",
                "parameters": [
                    {
                        "description": "User message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: \u003ctoken\u003e\\\\n\\\\n",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "strategist unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/strategies": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all 57+ backtest strategies. Use ?category= to filter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backtest"
                ],
                "summary": "List available strategies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "trend | momentum | volatility | reversal | composite | session | expression",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "strategies array + total count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns gateway status and NATS connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BacktestReport": {
            "type": "object",
            "properties": {
                "annualized_volatility_pct": {
                    "type": "number"
                },
                "avg_drawdown_pct": {
                    "type": "number"
                },
                "avg_loss_pct": {
                    "type": "number"
                },
                "avg_trade_duration_hours": {
                    "type": "number"
                },
                "avg_win_pct": {
                    "type": "number"
                },
                "cagr_pct": {
                    "type": "number"
                },
                "calmar_ratio": {
                    "type": "number"
                },
                "expectancy": {
                    "type": "number"
                },
                "final_equity": {
                    "type": "number"
                },
                "initial_capital": {
                    "description": "Capital",
                    "type": "number"
                },
                "max_consecutive_losses": {
                    "type": "integer"
                },
                "max_dd_duration_bars": {
                    "type": "integer"
                },
                "max_drawdown_pct": {
                    "description": "Drawdown",
                    "type": "number"
                },
                "profit_factor": {
                    "type": "number"
                },
                "sharpe_ratio": {
                    "description": "Risk-adjusted",
                    "type": "number"
                },
                "sortino_ratio": {
                    "type": "number"
                },
                "strategy": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "total_return_pct": {
                    "description": "Return metrics",
                    "type": "number"
                },
                "total_trades": {
                    "description": "Trade stats",
                    "type": "integer"
                },
                "win_rate_pct": {
                    "type": "number"
                }
            }
        },
        "handler.BacktestRequest": {
            "type": "object",
            "required": [
                "strategy",
                "symbol"
            ],
            "properties": {
                "commission_pct": {
                    "description": "fraction, e.g. 0.0003",
                    "type": "number"
                },
                "exchange": {
                    "description": "\"vn\" | \"us\" | \"crypto\"",
                    "type": "string"
                },
                "exit": {
                    "description": "Optional exit overrides",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.ExitConfig"
                        }
                    ]
                },
                "from": {
                    "description": "Date range (\"YYYY-MM-DD\")",
                    "type": "string"
                },
                "initial_capital": {
                    "description": "Capital \u0026 costs",
                    "type": "number"
                },
                "market_hours_only": {
                    "description": "Market hours filter",
                    "type": "boolean"
                },
                "params": {
                    "description": "Strategy params — flat JSON object or CEL entry/exit strings",
                    "type": "object",
                    "additionalProperties": {}
                },
                "slippage_pct": {
                    "description": "fraction, e.g. 0.001",
                    "type": "number"
                },
                "strategy": {
                    "description": "Required",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "handler.CelBacktestRequest": {
            "type": "object",
            "required": [
                "entry",
                "exit",
                "symbol"
            ],
            "properties": {
                "commission_pct": {
                    "type": "number"
                },
                "entry": {
                    "description": "CEL expression, e.g. \"rsi_14 \u003c 30.0\"",
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "exit": {
                    "description": "CEL expression, e.g. \"rsi_14 \u003e 70.0\"",
                    "type": "string"
                },
                "exit_rules": {
                    "description": "Optional exit overrides",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.ExitConfig"
                        }
                    ]
                },
                "from": {
                    "description": "Date range (\"YYYY-MM-DD\")",
                    "type": "string"
                },
                "initial_capital": {
                    "description": "Capital \u0026 costs",
                    "type": "number"
                },
                "market_hours_only": {
                    "description": "Market hours filter",
                    "type": "boolean"
                },
                "slippage_pct": {
                    "type": "number"
                },
                "symbol": {
                    "description": "Required",
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "handler.ChatRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ChatResponse": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "handler.ExitConfig": {
            "type": "object",
            "properties": {
                "max_bars_held": {
                    "type": "integer"
                },
                "stop_loss_pct": {
                    "type": "number"
                },
                "take_profit_pct": {
                    "type": "number"
                },
                "trailing_stop_pct": {
                    "type": "number"
                },
                "use_pattern_target": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token — prefix with \"Bearer \"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Mallow API Gateway",
	Description:      "Gateway for Mallow algorithmic trading system.\n\nAll protected routes require a Bearer JWT token obtained from the Identity service (`/api/v1/auth/login`).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
