[package]
name = "alm-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
alm-core    = { workspace = true }
anyhow      = { workspace = true }
serde       = { workspace = true }
tracing     = { workspace = true }
metrics     = { workspace = true }
parking_lot = "0.12"
dashmap     = "6"

[dev-dependencies]
tokio    = { workspace = true }
tempfile = "3"
