// Mallow Trading System — Protobuf message definitions
// Single source of truth for inter-service communication via NATS.
//
// NATS subjects:
//   ticks.{class}.{symbol}  ← stream-data → orchestrator (raw ticks, JSON)
//   bars.{symbol}           ← orchestrator → signal-engine (aggregated bars, protobuf)
//   signals.{symbol}        ← signal-engine → orchestrator
//   engine.configure        ← orchestrator → signal-engine
//   engine.reset            ← orchestrator → signal-engine

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: market.proto

package market

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BarMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`  // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`   // symbol
	O             float64                `protobuf:"fixed64,3,opt,name=o,proto3" json:"o,omitempty"` // open
	H             float64                `protobuf:"fixed64,4,opt,name=h,proto3" json:"h,omitempty"` // high
	L             float64                `protobuf:"fixed64,5,opt,name=l,proto3" json:"l,omitempty"` // low
	C             float64                `protobuf:"fixed64,6,opt,name=c,proto3" json:"c,omitempty"` // close
	V             float64                `protobuf:"fixed64,7,opt,name=v,proto3" json:"v,omitempty"` // volume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarMsg) Reset() {
	*x = BarMsg{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarMsg) ProtoMessage() {}

func (x *BarMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarMsg.ProtoReflect.Descriptor instead.
func (*BarMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *BarMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *BarMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *BarMsg) GetO() float64 {
	if x != nil {
		return x.O
	}
	return 0
}

func (x *BarMsg) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BarMsg) GetL() float64 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *BarMsg) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *BarMsg) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

type SignalMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`                // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`                 // symbol
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`             // "long" | "short" | "close"
	Strength      float64                `protobuf:"fixed64,4,opt,name=strength,proto3" json:"strength,omitempty"` // [0.0, 1.0]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMsg) Reset() {
	*x = SignalMsg{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMsg) ProtoMessage() {}

func (x *SignalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMsg.ProtoReflect.Descriptor instead.
func (*SignalMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *SignalMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *SignalMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *SignalMsg) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *SignalMsg) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*SignalMsg           `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *SignalResponse) GetSignals() []*SignalMsg {
	if x != nil {
		return x.Signals
	}
	return nil
}

type ConfigMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`                                                                         // "ma_crossover" | "rsi_mean_rev" | ...
	Params        map[string]float64     `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // strategy parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMsg) Reset() {
	*x = ConfigMsg{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMsg) ProtoMessage() {}

func (x *ConfigMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMsg.ProtoReflect.Descriptor instead.
func (*ConfigMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigMsg) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ConfigMsg) GetParams() map[string]float64 {
	if x != nil {
		return x.Params
	}
	return nil
}

type ResetMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // empty = reset all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMsg) Reset() {
	*x = ResetMsg{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMsg) ProtoMessage() {}

func (x *ResetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMsg.ProtoReflect.Descriptor instead.
func (*ResetMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *ResetMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x06market\"j\n" +
	"\x06BarMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\f\n" +
	"\x01o\x18\x03 \x01(\x01R\x01o\x12\f\n" +
	"\x01h\x18\x04 \x01(\x01R\x01h\x12\f\n" +
	"\x01l\x18\x05 \x01(\x01R\x01l\x12\f\n" +
	"\x01c\x18\x06 \x01(\x01R\x01c\x12\f\n" +
	"\x01v\x18\a \x01(\x01R\x01v\"U\n" +
	"\tSignalMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\x01R\bstrength\"=\n" +
	"\x0eSignalResponse\x12+\n" +
	"\asignals\x18\x01 \x03(\v2\x11.market.SignalMsgR\asignals\"\x99\x01\n" +
	"\tConfigMsg\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x125\n" +
	"\x06params\x18\x02 \x03(\v2\x1d.market.ConfigMsg.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\"\n" +
	"\bResetMsg\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbolB\x15Z\x13thesis/proto/marketb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_market_proto_goTypes = []any{
	(*BarMsg)(nil),         // 0: market.BarMsg
	(*SignalMsg)(nil),      // 1: market.SignalMsg
	(*SignalResponse)(nil), // 2: market.SignalResponse
	(*ConfigMsg)(nil),      // 3: market.ConfigMsg
	(*ResetMsg)(nil),       // 4: market.ResetMsg
	nil,                    // 5: market.ConfigMsg.ParamsEntry
}
var file_market_proto_depIdxs = []int32{
	1, // 0: market.SignalResponse.signals:type_name -> market.SignalMsg
	5, // 1: market.ConfigMsg.params:type_name -> market.ConfigMsg.ParamsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
