// Engine handshake and health messages: ping, heartbeat, ready.
//
// NATS subjects:
//   engine.ping       ← helm → herald (req/rep → PingResponse)
//   engine.heartbeat  ← helm → herald (req/rep → HeartbeatResponse)
//   engine.ready      ← herald → helm  (JetStream publish on startup)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// engine.ping — request: empty payload
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Hands         int32                  `protobuf:"varint,2,opt,name=hands,proto3" json:"hands,omitempty"` // total registered hands
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	HeraldId      string                 `protobuf:"bytes,4,opt,name=herald_id,json=heraldId,proto3" json:"herald_id,omitempty"` // instance identifier — changes on restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetHands() int32 {
	if x != nil {
		return x.Hands
	}
	return 0
}

func (x *PingResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *PingResponse) GetHeraldId() string {
	if x != nil {
		return x.HeraldId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HelmId        string                 `protobuf:"bytes,1,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"`
	Hands         []string               `protobuf:"bytes,2,rep,name=hands,proto3" json:"hands,omitempty"` // hand_ids expected to be registered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRequest) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

func (x *HeartbeatRequest) GetHands() []string {
	if x != nil {
		return x.Hands
	}
	return nil
}

type HeartbeatResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Ok         bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Missing    []string               `protobuf:"bytes,2,rep,name=missing,proto3" json:"missing,omitempty"`       // not in registry → helm must re-register
	Registered []string               `protobuf:"bytes,3,rep,name=registered,proto3" json:"registered,omitempty"` // confirmed present
	// Present in herald's registry under helm_id but absent from req.hands.
	// Catches stale registrations after helm forgot about them (e.g. restart
	// with new state and the original deregister was lost in transit).
	Orphan        []string `protobuf:"bytes,4,rep,name=orphan,proto3" json:"orphan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetMissing() []string {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *HeartbeatResponse) GetRegistered() []string {
	if x != nil {
		return x.Registered
	}
	return nil
}

func (x *HeartbeatResponse) GetOrphan() []string {
	if x != nil {
		return x.Orphan
	}
	return nil
}

// engine.ready — JetStream publish on herald startup.
// Consumers (helm) subscribe to detect herald restarts and re-register hands.
type ReadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeraldId      string                 `protobuf:"bytes,1,opt,name=herald_id,json=heraldId,proto3" json:"herald_id,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Tf            string                 `protobuf:"bytes,3,opt,name=tf,proto3" json:"tf,omitempty"`           // base timeframe (e.g. "M1")
	Symbols       []string               `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty"` // currently ingested symbols
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyEvent) Reset() {
	*x = ReadyEvent{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyEvent) ProtoMessage() {}

func (x *ReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyEvent.ProtoReflect.Descriptor instead.
func (*ReadyEvent) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ReadyEvent) GetHeraldId() string {
	if x != nil {
		return x.HeraldId
	}
	return ""
}

func (x *ReadyEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ReadyEvent) GetTf() string {
	if x != nil {
		return x.Tf
	}
	return ""
}

func (x *ReadyEvent) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x06market\"n\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05hands\x18\x02 \x01(\x05R\x05hands\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\x12\x1b\n" +
	"\therald_id\x18\x04 \x01(\tR\bheraldId\"A\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahelm_id\x18\x01 \x01(\tR\x06helmId\x12\x14\n" +
	"\x05hands\x18\x02 \x03(\tR\x05hands\"u\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amissing\x18\x02 \x03(\tR\amissing\x12\x1e\n" +
	"\n" +
	"registered\x18\x03 \x03(\tR\n" +
	"registered\x12\x16\n" +
	"\x06orphan\x18\x04 \x03(\tR\x06orphan\"c\n" +
	"\n" +
	"ReadyEvent\x12\x1b\n" +
	"\therald_id\x18\x01 \x01(\tR\bheraldId\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x0e\n" +
	"\x02tf\x18\x03 \x01(\tR\x02tf\x12\x18\n" +
	"\asymbols\x18\x04 \x03(\tR\asymbolsb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_engine_proto_goTypes = []any{
	(*PingResponse)(nil),      // 0: market.PingResponse
	(*HeartbeatRequest)(nil),  // 1: market.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 2: market.HeartbeatResponse
	(*ReadyEvent)(nil),        // 3: market.ReadyEvent
}
var file_engine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
