// Mallow Trading System — Protobuf message definitions
// Single source of truth for inter-service communication via NATS.
//
// NATS subjects:
//   bars.{symbol}       ← herald → helm (aggregated OHLCV bars)
//   signals             ← herald → helm (SignalResponse, hand_id+helm_id in payload)
//   engine.reset        ← helm → herald
//   engine.register     ← helm → herald (req/rep)
//   engine.deregister   ← helm → herald (req/rep)
//   engine.list         ← helm → herald (req/rep → HandListResponse)
//   engine.ping         ← helm → herald (req/rep → PingResponse)
//   engine.heartbeat    ← helm → herald (req/rep → HeartbeatResponse)
//   engine.ready        ← herald → helm (JetStream publish on startup)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`        // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`         // symbol (normalized uppercase, e.g. "BTCUSDT")
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"` // asset class: "crypto" | "stocks" | "forex"
	Src           string                 `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`     // source: "binance" | "alpaca" | "okx"
	P             float64                `protobuf:"fixed64,5,opt,name=p,proto3" json:"p,omitempty"`       // last price
	V             float64                `protobuf:"fixed64,6,opt,name=v,proto3" json:"v,omitempty"`       // volume (trade qty)
	Bid           float64                `protobuf:"fixed64,7,opt,name=bid,proto3" json:"bid,omitempty"`   // bid (forex only)
	Ask           float64                `protobuf:"fixed64,8,opt,name=ask,proto3" json:"ask,omitempty"`   // ask (forex only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickMsg) Reset() {
	*x = TickMsg{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMsg) ProtoMessage() {}

func (x *TickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMsg.ProtoReflect.Descriptor instead.
func (*TickMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *TickMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *TickMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *TickMsg) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *TickMsg) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *TickMsg) GetP() float64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *TickMsg) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *TickMsg) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *TickMsg) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

type BarMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`  // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`   // symbol
	O             float64                `protobuf:"fixed64,3,opt,name=o,proto3" json:"o,omitempty"` // open
	H             float64                `protobuf:"fixed64,4,opt,name=h,proto3" json:"h,omitempty"` // high
	L             float64                `protobuf:"fixed64,5,opt,name=l,proto3" json:"l,omitempty"` // low
	C             float64                `protobuf:"fixed64,6,opt,name=c,proto3" json:"c,omitempty"` // close
	V             float64                `protobuf:"fixed64,7,opt,name=v,proto3" json:"v,omitempty"` // volume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarMsg) Reset() {
	*x = BarMsg{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarMsg) ProtoMessage() {}

func (x *BarMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarMsg.ProtoReflect.Descriptor instead.
func (*BarMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *BarMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *BarMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *BarMsg) GetO() float64 {
	if x != nil {
		return x.O
	}
	return 0
}

func (x *BarMsg) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BarMsg) GetL() float64 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *BarMsg) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *BarMsg) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

type SignalMsg struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	T        int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`                // Unix milliseconds
	S        string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`                 // symbol
	Dir      string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`             // "long" | "short" | "exit"
	Strength float64                `protobuf:"fixed64,4,opt,name=strength,proto3" json:"strength,omitempty"` // conviction [0.0, 1.0] — derived from indicator values
	// Entry reference price (bar.close at signal time).
	// Helm uses this for informational purposes; actual fill is at next bar open.
	Price *float64 `protobuf:"fixed64,9,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// Exit levels. Absolute price by default; deltas from fill_price if is_offset=true.
	TargetPrice *float64 `protobuf:"fixed64,5,opt,name=target_price,json=targetPrice,proto3,oneof" json:"target_price,omitempty"`
	StopPrice   *float64 `protobuf:"fixed64,6,opt,name=stop_price,json=stopPrice,proto3,oneof" json:"stop_price,omitempty"`
	// When true, target_price and stop_price are offsets from fill_price.
	// Helm computes: actual_tp = fill_price + target_price
	//
	//	actual_sl = fill_price - stop_price
	IsOffset *bool `protobuf:"varint,10,opt,name=is_offset,json=isOffset,proto3,oneof" json:"is_offset,omitempty"`
	// Human-readable reason for this signal — logged by helm for auditability.
	// Not used for execution logic. E.g. "ema9 cross above H4 ema20, rsi < 60".
	Reason *string `protobuf:"bytes,11,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// ATR (Average True Range) at bar close — forwarded from the herald ledger.
	// Used by helm's tactician for ATR-based stop-loss / take-profit sizing and
	// the volatility position-sizing mode. Zero when the strategy does not use ATR.
	Atr *float64 `protobuf:"fixed64,12,opt,name=atr,proto3,oneof" json:"atr,omitempty"`
	// Pattern metadata (populated by pattern_breakout strategy only).
	PatternKind   *string  `protobuf:"bytes,7,opt,name=pattern_kind,json=patternKind,proto3,oneof" json:"pattern_kind,omitempty"`
	Confidence    *float64 `protobuf:"fixed64,8,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMsg) Reset() {
	*x = SignalMsg{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMsg) ProtoMessage() {}

func (x *SignalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMsg.ProtoReflect.Descriptor instead.
func (*SignalMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *SignalMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *SignalMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *SignalMsg) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *SignalMsg) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *SignalMsg) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *SignalMsg) GetTargetPrice() float64 {
	if x != nil && x.TargetPrice != nil {
		return *x.TargetPrice
	}
	return 0
}

func (x *SignalMsg) GetStopPrice() float64 {
	if x != nil && x.StopPrice != nil {
		return *x.StopPrice
	}
	return 0
}

func (x *SignalMsg) GetIsOffset() bool {
	if x != nil && x.IsOffset != nil {
		return *x.IsOffset
	}
	return false
}

func (x *SignalMsg) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *SignalMsg) GetAtr() float64 {
	if x != nil && x.Atr != nil {
		return *x.Atr
	}
	return 0
}

func (x *SignalMsg) GetPatternKind() string {
	if x != nil && x.PatternKind != nil {
		return *x.PatternKind
	}
	return ""
}

func (x *SignalMsg) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

// One hand emits at most one signal per bar.
type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *SignalMsg             `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	HelmId        string                 `protobuf:"bytes,2,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"` // owning helm — used for routing on the consumer side
	HandId        string                 `protobuf:"bytes,3,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"` // target hand
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *SignalResponse) GetSignal() *SignalMsg {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *SignalResponse) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

func (x *SignalResponse) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

type ResetMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // empty = reset all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMsg) Reset() {
	*x = ResetMsg{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMsg) ProtoMessage() {}

func (x *ResetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMsg.ProtoReflect.Descriptor instead.
func (*ResetMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *ResetMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type RegisterMsg struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	HandId string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"` // unique hand identifier (e.g. "hand_ema_btc_001")
	Symbol string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`               // e.g. "BTCUSDT"
	Script string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`               // full strategy script source
	// Timeframe the hand operates at (e.g. "M1", "H1", "D1") — REQUIRED.
	// Strategies are calibrated to a specific TF (a 14-period EMA on M1 vs H1
	// means completely different things), so register must declare it explicitly.
	// Herald resamples incoming base-TF bars to this TF before running the script.
	// Empty string is rejected by herald with a clear error.
	Timeframe string `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	HelmId    string `protobuf:"bytes,5,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"` // owning helm — used for routing in SignalResponse
	// Auto-expiry rules (optional — omit for permanent hands).
	ExpiresAtMs   *int64 `protobuf:"varint,6,opt,name=expires_at_ms,json=expiresAtMs,proto3,oneof" json:"expires_at_ms,omitempty"` // Unix ms TTL; auto-deregister after
	MaxBars       *int32 `protobuf:"varint,7,opt,name=max_bars,json=maxBars,proto3,oneof" json:"max_bars,omitempty"`               // auto-expire after N bars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	mi := &file_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterMsg) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *RegisterMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegisterMsg) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *RegisterMsg) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *RegisterMsg) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

func (x *RegisterMsg) GetExpiresAtMs() int64 {
	if x != nil && x.ExpiresAtMs != nil {
		return *x.ExpiresAtMs
	}
	return 0
}

func (x *RegisterMsg) GetMaxBars() int32 {
	if x != nil && x.MaxBars != nil {
		return *x.MaxBars
	}
	return 0
}

type DeregisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandId        string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"` // hand to remove; empty = remove all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterMsg) Reset() {
	*x = DeregisterMsg{}
	mi := &file_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterMsg) ProtoMessage() {}

func (x *DeregisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterMsg.ProtoReflect.Descriptor instead.
func (*DeregisterMsg) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterMsg) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

type HandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandId        string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Script        string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	Timeframe     string                 `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	HelmId        string                 `protobuf:"bytes,5,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandInfo) Reset() {
	*x = HandInfo{}
	mi := &file_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandInfo) ProtoMessage() {}

func (x *HandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandInfo.ProtoReflect.Descriptor instead.
func (*HandInfo) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{7}
}

func (x *HandInfo) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *HandInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HandInfo) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *HandInfo) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *HandInfo) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

type HandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hands         []*HandInfo            `protobuf:"bytes,1,rep,name=hands,proto3" json:"hands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandListResponse) Reset() {
	*x = HandListResponse{}
	mi := &file_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandListResponse) ProtoMessage() {}

func (x *HandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandListResponse.ProtoReflect.Descriptor instead.
func (*HandListResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{8}
}

func (x *HandListResponse) GetHands() []*HandInfo {
	if x != nil {
		return x.Hands
	}
	return nil
}

// engine.ping — request: empty payload, response: PingResponse
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Hands         int32                  `protobuf:"varint,2,opt,name=hands,proto3" json:"hands,omitempty"` // total registered hands
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	HeraldId      string                 `protobuf:"bytes,4,opt,name=herald_id,json=heraldId,proto3" json:"herald_id,omitempty"` // instance identifier — changes on restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetHands() int32 {
	if x != nil {
		return x.Hands
	}
	return 0
}

func (x *PingResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *PingResponse) GetHeraldId() string {
	if x != nil {
		return x.HeraldId
	}
	return ""
}

// engine.heartbeat — helm sends list of expected hand_ids, herald returns diff
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HelmId        string                 `protobuf:"bytes,1,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"`
	Hands         []string               `protobuf:"bytes,2,rep,name=hands,proto3" json:"hands,omitempty"` // hand_ids expected to be registered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

func (x *HeartbeatRequest) GetHands() []string {
	if x != nil {
		return x.Hands
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Missing       []string               `protobuf:"bytes,2,rep,name=missing,proto3" json:"missing,omitempty"`       // not in registry → helm must re-register
	Registered    []string               `protobuf:"bytes,3,rep,name=registered,proto3" json:"registered,omitempty"` // confirmed present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetMissing() []string {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *HeartbeatResponse) GetRegistered() []string {
	if x != nil {
		return x.Registered
	}
	return nil
}

// engine.ready — JetStream publish on herald startup
type ReadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeraldId      string                 `protobuf:"bytes,1,opt,name=herald_id,json=heraldId,proto3" json:"herald_id,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Tf            string                 `protobuf:"bytes,3,opt,name=tf,proto3" json:"tf,omitempty"`           // base timeframe (e.g. "M1")
	Symbols       []string               `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty"` // currently ingested symbols
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyEvent) Reset() {
	*x = ReadyEvent{}
	mi := &file_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyEvent) ProtoMessage() {}

func (x *ReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyEvent.ProtoReflect.Descriptor instead.
func (*ReadyEvent) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{12}
}

func (x *ReadyEvent) GetHeraldId() string {
	if x != nil {
		return x.HeraldId
	}
	return ""
}

func (x *ReadyEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ReadyEvent) GetTf() string {
	if x != nil {
		return x.Tf
	}
	return ""
}

func (x *ReadyEvent) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x06market\"\x8d\x01\n" +
	"\aTickMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\f\n" +
	"\x01p\x18\x05 \x01(\x01R\x01p\x12\f\n" +
	"\x01v\x18\x06 \x01(\x01R\x01v\x12\x10\n" +
	"\x03bid\x18\a \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\b \x01(\x01R\x03ask\"j\n" +
	"\x06BarMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\f\n" +
	"\x01o\x18\x03 \x01(\x01R\x01o\x12\f\n" +
	"\x01h\x18\x04 \x01(\x01R\x01h\x12\f\n" +
	"\x01l\x18\x05 \x01(\x01R\x01l\x12\f\n" +
	"\x01c\x18\x06 \x01(\x01R\x01c\x12\f\n" +
	"\x01v\x18\a \x01(\x01R\x01v\"\xca\x03\n" +
	"\tSignalMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\x01R\bstrength\x12\x19\n" +
	"\x05price\x18\t \x01(\x01H\x00R\x05price\x88\x01\x01\x12&\n" +
	"\ftarget_price\x18\x05 \x01(\x01H\x01R\vtargetPrice\x88\x01\x01\x12\"\n" +
	"\n" +
	"stop_price\x18\x06 \x01(\x01H\x02R\tstopPrice\x88\x01\x01\x12 \n" +
	"\tis_offset\x18\n" +
	" \x01(\bH\x03R\bisOffset\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\v \x01(\tH\x04R\x06reason\x88\x01\x01\x12\x15\n" +
	"\x03atr\x18\f \x01(\x01H\x05R\x03atr\x88\x01\x01\x12&\n" +
	"\fpattern_kind\x18\a \x01(\tH\x06R\vpatternKind\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\b \x01(\x01H\aR\n" +
	"confidence\x88\x01\x01B\b\n" +
	"\x06_priceB\x0f\n" +
	"\r_target_priceB\r\n" +
	"\v_stop_priceB\f\n" +
	"\n" +
	"_is_offsetB\t\n" +
	"\a_reasonB\x06\n" +
	"\x04_atrB\x0f\n" +
	"\r_pattern_kindB\r\n" +
	"\v_confidence\"m\n" +
	"\x0eSignalResponse\x12)\n" +
	"\x06signal\x18\x01 \x01(\v2\x11.market.SignalMsgR\x06signal\x12\x17\n" +
	"\ahelm_id\x18\x02 \x01(\tR\x06helmId\x12\x17\n" +
	"\ahand_id\x18\x03 \x01(\tR\x06handId\"\"\n" +
	"\bResetMsg\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xf5\x01\n" +
	"\vRegisterMsg\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12\x1c\n" +
	"\ttimeframe\x18\x04 \x01(\tR\ttimeframe\x12\x17\n" +
	"\ahelm_id\x18\x05 \x01(\tR\x06helmId\x12'\n" +
	"\rexpires_at_ms\x18\x06 \x01(\x03H\x00R\vexpiresAtMs\x88\x01\x01\x12\x1e\n" +
	"\bmax_bars\x18\a \x01(\x05H\x01R\amaxBars\x88\x01\x01B\x10\n" +
	"\x0e_expires_at_msB\v\n" +
	"\t_max_bars\"(\n" +
	"\rDeregisterMsg\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\"\x8a\x01\n" +
	"\bHandInfo\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12\x1c\n" +
	"\ttimeframe\x18\x04 \x01(\tR\ttimeframe\x12\x17\n" +
	"\ahelm_id\x18\x05 \x01(\tR\x06helmId\":\n" +
	"\x10HandListResponse\x12&\n" +
	"\x05hands\x18\x01 \x03(\v2\x10.market.HandInfoR\x05hands\"n\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05hands\x18\x02 \x01(\x05R\x05hands\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\x12\x1b\n" +
	"\therald_id\x18\x04 \x01(\tR\bheraldId\"A\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahelm_id\x18\x01 \x01(\tR\x06helmId\x12\x14\n" +
	"\x05hands\x18\x02 \x03(\tR\x05hands\"]\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amissing\x18\x02 \x03(\tR\amissing\x12\x1e\n" +
	"\n" +
	"registered\x18\x03 \x03(\tR\n" +
	"registered\"c\n" +
	"\n" +
	"ReadyEvent\x12\x1b\n" +
	"\therald_id\x18\x01 \x01(\tR\bheraldId\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x0e\n" +
	"\x02tf\x18\x03 \x01(\tR\x02tf\x12\x18\n" +
	"\asymbols\x18\x04 \x03(\tR\asymbolsB\x15Z\x13mallow/proto/marketb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_market_proto_goTypes = []any{
	(*TickMsg)(nil),           // 0: market.TickMsg
	(*BarMsg)(nil),            // 1: market.BarMsg
	(*SignalMsg)(nil),         // 2: market.SignalMsg
	(*SignalResponse)(nil),    // 3: market.SignalResponse
	(*ResetMsg)(nil),          // 4: market.ResetMsg
	(*RegisterMsg)(nil),       // 5: market.RegisterMsg
	(*DeregisterMsg)(nil),     // 6: market.DeregisterMsg
	(*HandInfo)(nil),          // 7: market.HandInfo
	(*HandListResponse)(nil),  // 8: market.HandListResponse
	(*PingResponse)(nil),      // 9: market.PingResponse
	(*HeartbeatRequest)(nil),  // 10: market.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 11: market.HeartbeatResponse
	(*ReadyEvent)(nil),        // 12: market.ReadyEvent
}
var file_market_proto_depIdxs = []int32{
	2, // 0: market.SignalResponse.signal:type_name -> market.SignalMsg
	7, // 1: market.HandListResponse.hands:type_name -> market.HandInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	file_market_proto_msgTypes[2].OneofWrappers = []any{}
	file_market_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
