// Hand registry messages: register/deregister hands with herald's signal engine.
//
// NATS subjects:
//   engine.reset       ← helm → herald (pub, no reply)
//   engine.register    ← helm → herald (req/rep → JSON ack {"ok":bool})
//   engine.deregister  ← helm → herald (req/rep → JSON ack {"ok":bool})
//   engine.list        ← helm → herald (req/rep → HandListResponse)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // empty = reset all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMsg) Reset() {
	*x = ResetMsg{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMsg) ProtoMessage() {}

func (x *ResetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMsg.ProtoReflect.Descriptor instead.
func (*ResetMsg) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ResetMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type RegisterMsg struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	HandId string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"` // unique hand identifier
	Symbol string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`               // raw ticker: "BTCUSDT", "BTC-USDT"
	Script string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`               // full Rhai strategy script source
	// Timeframe the hand evaluates at (e.g. "M1", "H1", "D1") — REQUIRED.
	// Strategies are calibrated to a specific TF (a 14-period EMA on M1 vs H1
	// means completely different things), so register must declare it explicitly.
	// Herald resamples incoming base-TF bars to this TF before running the script.
	// Empty string is rejected by herald with a clear error.
	Timeframe string `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	HelmId    string `protobuf:"bytes,5,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"` // owning helm — used for routing in SignalResponse
	// Auto-expiry (optional — omit for permanent hands).
	ExpiresAtMs *int64 `protobuf:"varint,6,opt,name=expires_at_ms,json=expiresAtMs,proto3,oneof" json:"expires_at_ms,omitempty"` // Unix ms; auto-deregister after this time
	MaxBars     *int32 `protobuf:"varint,7,opt,name=max_bars,json=maxBars,proto3,oneof" json:"max_bars,omitempty"`               // auto-deregister after N bars received
	// Instrument descriptor — tells herald which exchange feed to bind against.
	// Herald builds the internal ledger key as "{exchange}:{symbol}".
	// Empty exchange is accepted for tests / backtest-only setups.
	Exchange      string `protobuf:"bytes,8,opt,name=exchange,proto3" json:"exchange,omitempty"`                  // "binance" | "okx" | "alpaca" | "bybit" | ""
	IsFuture      bool   `protobuf:"varint,9,opt,name=is_future,json=isFuture,proto3" json:"is_future,omitempty"` // false = spot; true = perpetual / futures contract
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMsg) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *RegisterMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegisterMsg) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *RegisterMsg) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *RegisterMsg) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

func (x *RegisterMsg) GetExpiresAtMs() int64 {
	if x != nil && x.ExpiresAtMs != nil {
		return *x.ExpiresAtMs
	}
	return 0
}

func (x *RegisterMsg) GetMaxBars() int32 {
	if x != nil && x.MaxBars != nil {
		return *x.MaxBars
	}
	return 0
}

func (x *RegisterMsg) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *RegisterMsg) GetIsFuture() bool {
	if x != nil {
		return x.IsFuture
	}
	return false
}

type DeregisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandId        string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"` // hand to remove; empty = remove all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterMsg) Reset() {
	*x = DeregisterMsg{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterMsg) ProtoMessage() {}

func (x *DeregisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterMsg.ProtoReflect.Descriptor instead.
func (*DeregisterMsg) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterMsg) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

type HandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandId        string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // raw ticker
	Script        string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	Timeframe     string                 `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	HelmId        string                 `protobuf:"bytes,5,opt,name=helm_id,json=helmId,proto3" json:"helm_id,omitempty"`
	Exchange      string                 `protobuf:"bytes,6,opt,name=exchange,proto3" json:"exchange,omitempty"`
	IsFuture      bool                   `protobuf:"varint,7,opt,name=is_future,json=isFuture,proto3" json:"is_future,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandInfo) Reset() {
	*x = HandInfo{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandInfo) ProtoMessage() {}

func (x *HandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandInfo.ProtoReflect.Descriptor instead.
func (*HandInfo) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HandInfo) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *HandInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HandInfo) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *HandInfo) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *HandInfo) GetHelmId() string {
	if x != nil {
		return x.HelmId
	}
	return ""
}

func (x *HandInfo) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *HandInfo) GetIsFuture() bool {
	if x != nil {
		return x.IsFuture
	}
	return false
}

type HandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hands         []*HandInfo            `protobuf:"bytes,1,rep,name=hands,proto3" json:"hands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandListResponse) Reset() {
	*x = HandListResponse{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandListResponse) ProtoMessage() {}

func (x *HandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandListResponse.ProtoReflect.Descriptor instead.
func (*HandListResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HandListResponse) GetHands() []*HandInfo {
	if x != nil {
		return x.Hands
	}
	return nil
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\x06market\"\"\n" +
	"\bResetMsg\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xae\x02\n" +
	"\vRegisterMsg\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12\x1c\n" +
	"\ttimeframe\x18\x04 \x01(\tR\ttimeframe\x12\x17\n" +
	"\ahelm_id\x18\x05 \x01(\tR\x06helmId\x12'\n" +
	"\rexpires_at_ms\x18\x06 \x01(\x03H\x00R\vexpiresAtMs\x88\x01\x01\x12\x1e\n" +
	"\bmax_bars\x18\a \x01(\x05H\x01R\amaxBars\x88\x01\x01\x12\x1a\n" +
	"\bexchange\x18\b \x01(\tR\bexchange\x12\x1b\n" +
	"\tis_future\x18\t \x01(\bR\bisFutureB\x10\n" +
	"\x0e_expires_at_msB\v\n" +
	"\t_max_bars\"(\n" +
	"\rDeregisterMsg\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\"\xc3\x01\n" +
	"\bHandInfo\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12\x1c\n" +
	"\ttimeframe\x18\x04 \x01(\tR\ttimeframe\x12\x17\n" +
	"\ahelm_id\x18\x05 \x01(\tR\x06helmId\x12\x1a\n" +
	"\bexchange\x18\x06 \x01(\tR\bexchange\x12\x1b\n" +
	"\tis_future\x18\a \x01(\bR\bisFuture\":\n" +
	"\x10HandListResponse\x12&\n" +
	"\x05hands\x18\x01 \x03(\v2\x10.market.HandInfoR\x05handsb\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_registry_proto_goTypes = []any{
	(*ResetMsg)(nil),         // 0: market.ResetMsg
	(*RegisterMsg)(nil),      // 1: market.RegisterMsg
	(*DeregisterMsg)(nil),    // 2: market.DeregisterMsg
	(*HandInfo)(nil),         // 3: market.HandInfo
	(*HandListResponse)(nil), // 4: market.HandListResponse
}
var file_registry_proto_depIdxs = []int32{
	3, // 0: market.HandListResponse.hands:type_name -> market.HandInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	file_registry_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
