// Mallow Trading System — Protobuf message definitions
// Single source of truth for inter-service communication via NATS.
//
// NATS subjects:
//   ticks.{class}.{symbol}  ← stream-data → orchestrator (raw ticks)
//   bars.{symbol}           ← orchestrator → signal-engine (aggregated bars)
//   signals.{symbol}        ← signal-engine → orchestrator
//   engine.configure        ← orchestrator → signal-engine
//   engine.reset            ← orchestrator → signal-engine

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`        // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`         // symbol (normalized uppercase, e.g. "BTCUSDT")
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"` // asset class: "crypto" | "stocks" | "forex"
	Src           string                 `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`     // source: "binance" | "alpaca" | "twelvedata" | "okx"
	P             float64                `protobuf:"fixed64,5,opt,name=p,proto3" json:"p,omitempty"`       // last price
	V             float64                `protobuf:"fixed64,6,opt,name=v,proto3" json:"v,omitempty"`       // volume (trade qty)
	Bid           float64                `protobuf:"fixed64,7,opt,name=bid,proto3" json:"bid,omitempty"`   // bid (forex only)
	Ask           float64                `protobuf:"fixed64,8,opt,name=ask,proto3" json:"ask,omitempty"`   // ask (forex only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickMsg) Reset() {
	*x = TickMsg{}
	mi := &file_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMsg) ProtoMessage() {}

func (x *TickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMsg.ProtoReflect.Descriptor instead.
func (*TickMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *TickMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *TickMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *TickMsg) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *TickMsg) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *TickMsg) GetP() float64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *TickMsg) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *TickMsg) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *TickMsg) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

type BarMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`  // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`   // symbol
	O             float64                `protobuf:"fixed64,3,opt,name=o,proto3" json:"o,omitempty"` // open
	H             float64                `protobuf:"fixed64,4,opt,name=h,proto3" json:"h,omitempty"` // high
	L             float64                `protobuf:"fixed64,5,opt,name=l,proto3" json:"l,omitempty"` // low
	C             float64                `protobuf:"fixed64,6,opt,name=c,proto3" json:"c,omitempty"` // close
	V             float64                `protobuf:"fixed64,7,opt,name=v,proto3" json:"v,omitempty"` // volume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarMsg) Reset() {
	*x = BarMsg{}
	mi := &file_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarMsg) ProtoMessage() {}

func (x *BarMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarMsg.ProtoReflect.Descriptor instead.
func (*BarMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *BarMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *BarMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *BarMsg) GetO() float64 {
	if x != nil {
		return x.O
	}
	return 0
}

func (x *BarMsg) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BarMsg) GetL() float64 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *BarMsg) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *BarMsg) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

type SignalMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`                // Unix milliseconds
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`                 // symbol
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`             // "long" | "short" | "close"
	Strength      float64                `protobuf:"fixed64,4,opt,name=strength,proto3" json:"strength,omitempty"` // [0.0, 1.0]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMsg) Reset() {
	*x = SignalMsg{}
	mi := &file_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMsg) ProtoMessage() {}

func (x *SignalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMsg.ProtoReflect.Descriptor instead.
func (*SignalMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{2}
}

func (x *SignalMsg) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *SignalMsg) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *SignalMsg) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *SignalMsg) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*SignalMsg           `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	OrchId        string                 `protobuf:"bytes,2,opt,name=orch_id,json=orchId,proto3" json:"orch_id,omitempty"` // owning orchestrator
	BotId         string                 `protobuf:"bytes,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`    // target bot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{3}
}

func (x *SignalResponse) GetSignals() []*SignalMsg {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *SignalResponse) GetOrchId() string {
	if x != nil {
		return x.OrchId
	}
	return ""
}

func (x *SignalResponse) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type ConfigMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`                                                                         // "ma_crossover" | "rsi_mean_rev" | ...
	Params        map[string]float64     `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // strategy parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMsg) Reset() {
	*x = ConfigMsg{}
	mi := &file_proto_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMsg) ProtoMessage() {}

func (x *ConfigMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMsg.ProtoReflect.Descriptor instead.
func (*ConfigMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigMsg) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ConfigMsg) GetParams() map[string]float64 {
	if x != nil {
		return x.Params
	}
	return nil
}

type ResetMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // empty = reset all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMsg) Reset() {
	*x = ResetMsg{}
	mi := &file_proto_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMsg) ProtoMessage() {}

func (x *ResetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMsg.ProtoReflect.Descriptor instead.
func (*ResetMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{5}
}

func (x *ResetMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type RegisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`                // unique bot identifier (e.g. "bot_ema_btc_001")
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                           // e.g. "BTCUSDT"
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`                       // "ma_crossover" | "rsi_mean_rev" | ...
	ParamsJson    string                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // flat JSON params: {"fast": 20, "slow": 50}
	OrchId        string                 `protobuf:"bytes,10,opt,name=orch_id,json=orchId,proto3" json:"orch_id,omitempty"`            // owning orchestrator — used to build signal subject signals.{orch_id}.{bot_id}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	mi := &file_proto_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterMsg) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *RegisterMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegisterMsg) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *RegisterMsg) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *RegisterMsg) GetOrchId() string {
	if x != nil {
		return x.OrchId
	}
	return ""
}

type DeregisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"` // bot to remove; empty = remove all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterMsg) Reset() {
	*x = DeregisterMsg{}
	mi := &file_proto_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterMsg) ProtoMessage() {}

func (x *DeregisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterMsg.ProtoReflect.Descriptor instead.
func (*DeregisterMsg) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterMsg) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type BotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotInfo) Reset() {
	*x = BotInfo{}
	mi := &file_proto_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotInfo) ProtoMessage() {}

func (x *BotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotInfo.ProtoReflect.Descriptor instead.
func (*BotInfo) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{8}
}

func (x *BotInfo) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *BotInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BotInfo) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *BotInfo) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type BotListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*BotInfo             `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotListResponse) Reset() {
	*x = BotListResponse{}
	mi := &file_proto_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotListResponse) ProtoMessage() {}

func (x *BotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotListResponse.ProtoReflect.Descriptor instead.
func (*BotListResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{9}
}

func (x *BotListResponse) GetBots() []*BotInfo {
	if x != nil {
		return x.Bots
	}
	return nil
}

var File_proto_market_proto protoreflect.FileDescriptor

const file_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x12proto/market.proto\x12\x06market\"\x8d\x01\n" +
	"\aTickMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\f\n" +
	"\x01p\x18\x05 \x01(\x01R\x01p\x12\f\n" +
	"\x01v\x18\x06 \x01(\x01R\x01v\x12\x10\n" +
	"\x03bid\x18\a \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\b \x01(\x01R\x03ask\"j\n" +
	"\x06BarMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\f\n" +
	"\x01o\x18\x03 \x01(\x01R\x01o\x12\f\n" +
	"\x01h\x18\x04 \x01(\x01R\x01h\x12\f\n" +
	"\x01l\x18\x05 \x01(\x01R\x01l\x12\f\n" +
	"\x01c\x18\x06 \x01(\x01R\x01c\x12\f\n" +
	"\x01v\x18\a \x01(\x01R\x01v\"U\n" +
	"\tSignalMsg\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\x01R\bstrength\"=\n" +
	"\x0eSignalResponse\x12+\n" +
	"\asignals\x18\x01 \x03(\v2\x11.market.SignalMsgR\asignals\"\x99\x01\n" +
	"\tConfigMsg\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x125\n" +
	"\x06params\x18\x02 \x03(\v2\x1d.market.ConfigMsg.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\"\n" +
	"\bResetMsg\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"y\n" +
	"\vRegisterMsg\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\tR\n" +
	"paramsJson\"&\n" +
	"\rDeregisterMsg\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"u\n" +
	"\aBotInfo\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\tR\n" +
	"paramsJson\"6\n" +
	"\x0fBotListResponse\x12#\n" +
	"\x04bots\x18\x01 \x03(\v2\x0f.market.BotInfoR\x04botsB\x15Z\x13thesis/proto/marketb\x06proto3"

var (
	file_proto_market_proto_rawDescOnce sync.Once
	file_proto_market_proto_rawDescData []byte
)

func file_proto_market_proto_rawDescGZIP() []byte {
	file_proto_market_proto_rawDescOnce.Do(func() {
		file_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)))
	})
	return file_proto_market_proto_rawDescData
}

var file_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_market_proto_goTypes = []any{
	(*TickMsg)(nil),         // 0: market.TickMsg
	(*BarMsg)(nil),          // 1: market.BarMsg
	(*SignalMsg)(nil),       // 2: market.SignalMsg
	(*SignalResponse)(nil),  // 3: market.SignalResponse
	(*ConfigMsg)(nil),       // 4: market.ConfigMsg
	(*ResetMsg)(nil),        // 5: market.ResetMsg
	(*RegisterMsg)(nil),     // 6: market.RegisterMsg
	(*DeregisterMsg)(nil),   // 7: market.DeregisterMsg
	(*BotInfo)(nil),         // 8: market.BotInfo
	(*BotListResponse)(nil), // 9: market.BotListResponse
	nil,                     // 10: market.ConfigMsg.ParamsEntry
}
var file_proto_market_proto_depIdxs = []int32{
	2,  // 0: market.SignalResponse.signals:type_name -> market.SignalMsg
	10, // 1: market.ConfigMsg.params:type_name -> market.ConfigMsg.ParamsEntry
	8,  // 2: market.BotListResponse.bots:type_name -> market.BotInfo
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_market_proto_init() }
func file_proto_market_proto_init() {
	if File_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_market_proto_goTypes,
		DependencyIndexes: file_proto_market_proto_depIdxs,
		MessageInfos:      file_proto_market_proto_msgTypes,
	}.Build()
	File_proto_market_proto = out.File
	file_proto_market_proto_goTypes = nil
	file_proto_market_proto_depIdxs = nil
}
