//! # alm-ledger — live market state machine
//!
//! A process-local, thread-safe state container that keeps a **sliding bar
//! window** plus any number of **incremental indicators** per `(symbol, timeframe)`.
//! Both the bot registry (via strategy evaluation) and HTTP endpoints read
//! from the same ledger, so signals generated by live bots are always
//! computed off the exact same series that the chart API serves.
//!
//! ## Invariants
//!
//! 1. Indicator dedup is *spec-level*: registering the same
//!    [`IndicatorSpec`] twice produces a single shared instance.
//! 2. The bar window grows automatically when a large-period indicator is
//!    registered, up to `max(default, 5 × longest_period + display_tail)`.
//! 3. Out-of-order / duplicate bars are rejected — state is monotonic.
//! 4. Session-aware indicators (VWAP) are reset on a UTC-day rollover.
//!
//! ## Example
//!
//! ```rust,no_run
//! use std::sync::Arc;
//! use alm_ledger::{Ledger, LedgerConfig, IndicatorSpec};
//! use alm_core::{Bar, Timeframe};
//! use serde_json::json;
//!
//! let ledger = Arc::new(Ledger::new(LedgerConfig::default()));
//! // Acquire a live handle — drop releases the cell after a grace period.
//! let _h = ledger.acquire_indicator(
//!     "BTCUSDT",
//!     Timeframe::M1,
//!     IndicatorSpec::from_config(json!({"type":"ema","period":20}), None).unwrap(),
//! ).unwrap();
//! // feed bars from NATS / parquet bootstrap / test fixture
//! ledger.advance(Timeframe::M1, Bar::new(60_000, "BTCUSDT", 100.0, 101.0, 99.0, 100.5, 1.0)).unwrap();
//! let snap = ledger.snapshot("BTCUSDT", Timeframe::M1).unwrap();
//! assert_eq!(snap.bars.len(), 1);
//! ```

mod spec;
mod state;
mod ledger;
mod handle;
mod bootstrap;
mod warm_set;

pub use spec::IndicatorSpec;
pub use state::{
    AdvanceOutcome, IndicatorCell, IndicatorColumnSlice, IndicatorFields, IndicatorSeriesSlice,
    SymbolSnapshot, SymbolState,
};
pub use ledger::{Ledger, LedgerConfig, LedgerObserver, SymbolKey};
pub use handle::IndicatorHandle;
pub use bootstrap::{BootstrapJob, BootstrapReport};
pub use warm_set::default_warm_set;
