// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "List bots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by orchestrator ID",
                        "name": "orchestrator_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by account ID",
                        "name": "account_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BotListSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Create bot",
                "parameters": [
                    {
                        "description": "Bot create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateBotReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.BotSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/bots/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Get bot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BotSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Update bot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Bot update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateBotReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BotSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Delete bot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BotActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/bots/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Start bot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BotActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/bots/{id}/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Stop bot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BotActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "List orchestrators",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.OrchestratorListSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Get orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.OrchestratorDetailSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Update orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Orchestrator update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateOrchestratorReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.OrchestratorSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Disable orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Enable orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "List orchestrator orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.OrdersSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Pause orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/portfolio": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Get orchestrator portfolio summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PortfolioSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/positions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "List orchestrator positions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PositionsSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/resume": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "Resume orchestrator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ActionSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orchestrators/{id}/trades": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrators"
                ],
                "summary": "List orchestrator trades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Orchestrator ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TradesSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_module_orchesrator_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/signal-engine/configure": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signal-engine"
                ],
                "summary": "Configure signal engine strategy",
                "parameters": [
                    {
                        "description": "Signal engine strategy config",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ConfigureStrategyReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ConfigureStrategySuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_module_worker_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.BotHealthView": {
            "type": "object",
            "properties": {
                "last_error": {
                    "type": "string"
                },
                "last_error_at": {
                    "type": "string"
                },
                "last_order_at": {
                    "type": "string"
                },
                "last_signal_at": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "domain.BotMetricsView": {
            "type": "object",
            "properties": {
                "loss_count": {
                    "type": "integer"
                },
                "orders_failed": {
                    "type": "integer"
                },
                "orders_filled": {
                    "type": "integer"
                },
                "orders_placed": {
                    "type": "integer"
                },
                "signals_filtered": {
                    "type": "integer"
                },
                "signals_received": {
                    "type": "integer"
                },
                "total_pnl": {
                    "type": "number"
                },
                "trades_approved": {
                    "type": "integer"
                },
                "win_count": {
                    "type": "integer"
                }
            }
        },
        "domain.BotRiskConfig": {
            "type": "object",
            "properties": {
                "fixed_qty": {
                    "type": "number"
                },
                "max_position_pct": {
                    "type": "number"
                },
                "risk_per_trade_pct": {
                    "type": "number"
                },
                "size_mode": {
                    "type": "string"
                },
                "stop_loss_atr_mult": {
                    "type": "number"
                }
            }
        },
        "domain.BotSummary": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "health": {
                    "$ref": "#/definitions/domain.BotHealthView"
                },
                "id": {
                    "type": "string"
                },
                "metrics": {
                    "$ref": "#/definitions/domain.BotMetricsView"
                },
                "name": {
                    "type": "string"
                },
                "orchestrator_id": {
                    "type": "string"
                },
                "order_count": {
                    "type": "integer"
                },
                "risk": {
                    "$ref": "#/definitions/domain.BotRiskConfig"
                },
                "running": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "strategy": {
                    "$ref": "#/definitions/domain.StrategyConfig"
                },
                "symbols": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/domain.BotType"
                }
            }
        },
        "domain.BotType": {
            "type": "string",
            "enum": [
                "signal_follower",
                "manual",
                "dca",
                "grid"
            ],
            "x-enum-varnames": [
                "BotTypeSignalFollower",
                "BotTypeManual",
                "BotTypeDCA",
                "BotTypeGrid"
            ]
        },
        "domain.StrategyConfig": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        },
        "handler.ActionResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.ActionSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ActionResp"
                },
                "message": {
                    "type": "string",
                    "example": "Orchestrator enabled successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.BotActionResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.BotActionSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.BotActionResp"
                },
                "message": {
                    "type": "string",
                    "example": "Bot started successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.BotHealthResp": {
            "type": "object",
            "properties": {
                "last_error": {
                    "type": "string"
                },
                "last_error_at": {
                    "type": "string"
                },
                "last_order_at": {
                    "type": "string"
                },
                "last_signal_at": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "handler.BotListSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.BotSummary"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Bots retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.BotMetricsResp": {
            "type": "object",
            "properties": {
                "loss_count": {
                    "type": "integer"
                },
                "orders_failed": {
                    "type": "integer"
                },
                "orders_filled": {
                    "type": "integer"
                },
                "orders_placed": {
                    "type": "integer"
                },
                "signals_filtered": {
                    "type": "integer"
                },
                "signals_received": {
                    "type": "integer"
                },
                "total_pnl": {
                    "type": "number"
                },
                "trades_approved": {
                    "type": "integer"
                },
                "win_count": {
                    "type": "integer"
                }
            }
        },
        "handler.BotRiskConfigDTO": {
            "type": "object",
            "properties": {
                "fixed_qty": {
                    "type": "number"
                },
                "max_position_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "risk_per_trade_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "size_mode": {
                    "type": "string",
                    "enum": [
                        "fixed_fractional",
                        "fixed_qty",
                        "percent_equity"
                    ]
                },
                "stop_loss_atr_mult": {
                    "type": "number"
                }
            }
        },
        "handler.BotRiskResp": {
            "type": "object",
            "properties": {
                "fixed_qty": {
                    "type": "number"
                },
                "max_position_pct": {
                    "type": "number"
                },
                "risk_per_trade_pct": {
                    "type": "number"
                },
                "size_mode": {
                    "type": "string"
                },
                "stop_loss_atr_mult": {
                    "type": "number"
                }
            }
        },
        "handler.BotStrategyResp": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        },
        "handler.BotSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.BotSummary"
                },
                "message": {
                    "type": "string",
                    "example": "Bot retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.BotSummaryResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "health": {
                    "$ref": "#/definitions/handler.BotHealthResp"
                },
                "id": {
                    "type": "string"
                },
                "metrics": {
                    "$ref": "#/definitions/handler.BotMetricsResp"
                },
                "name": {
                    "type": "string"
                },
                "orchestrator_id": {
                    "type": "string"
                },
                "order_count": {
                    "type": "integer"
                },
                "risk": {
                    "$ref": "#/definitions/handler.BotRiskResp"
                },
                "running": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "strategy": {
                    "$ref": "#/definitions/handler.BotStrategyResp"
                },
                "symbols": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.ConfigureStrategyReq": {
            "type": "object",
            "required": [
                "strategy"
            ],
            "properties": {
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "strategy": {
                    "type": "string"
                }
            }
        },
        "handler.ConfigureStrategyResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "strategy": {
                    "type": "string"
                }
            }
        },
        "handler.ConfigureStrategySuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ConfigureStrategyResp"
                },
                "message": {
                    "type": "string",
                    "example": "Signal engine configured successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.CreateBotReq": {
            "type": "object",
            "required": [
                "name",
                "strategy",
                "symbols"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "orchestrator_id": {
                    "type": "string"
                },
                "risk": {
                    "$ref": "#/definitions/handler.BotRiskConfigDTO"
                },
                "strategy": {
                    "$ref": "#/definitions/handler.StrategyConfigDTO"
                },
                "symbols": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "enum": [
                        "signal_follower",
                        "manual",
                        "dca",
                        "grid"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.BotType"
                        }
                    ]
                }
            }
        },
        "handler.ExchangeConfigResp": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "broker_type": {
                    "type": "string"
                },
                "demo": {
                    "type": "boolean"
                },
                "testnet": {
                    "type": "boolean"
                }
            }
        },
        "handler.OrchestratorDetailResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "bots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.BotSummaryResp"
                    }
                },
                "capital": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "exchange": {
                    "$ref": "#/definitions/handler.ExchangeConfigResp"
                },
                "id": {
                    "type": "string"
                },
                "last_sync_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paused": {
                    "type": "boolean"
                },
                "risk": {
                    "$ref": "#/definitions/handler.RiskConfigDTO"
                },
                "running": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.OrchestratorDetailSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.OrchestratorDetailResp"
                },
                "message": {
                    "type": "string",
                    "example": "Orchestrator retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.OrchestratorListSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.OrchestratorResp"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Orchestrators retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.OrchestratorResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "capital": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "exchange": {
                    "$ref": "#/definitions/handler.ExchangeConfigResp"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "risk": {
                    "$ref": "#/definitions/handler.RiskConfigDTO"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.OrchestratorSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.OrchestratorResp"
                },
                "message": {
                    "type": "string",
                    "example": "Orchestrator updated successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.OrderResp": {
            "type": "object",
            "properties": {
                "bot_id": {
                    "type": "string"
                },
                "filled_avg_price": {
                    "type": "number"
                },
                "filled_qty": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "orchestrator_id": {
                    "type": "string"
                },
                "qty": {
                    "type": "number"
                },
                "side": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.OrdersSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.OrderResp"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Orders retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.PortfolioResp": {
            "type": "object",
            "properties": {
                "cash": {
                    "type": "number"
                },
                "current_drawdown_pct": {
                    "type": "number"
                },
                "daily_pnl": {
                    "type": "number"
                },
                "equity": {
                    "type": "number"
                },
                "initial_capital": {
                    "type": "number"
                },
                "max_drawdown_pct": {
                    "type": "number"
                },
                "open_positions": {
                    "type": "integer"
                },
                "positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.PositionResp"
                    }
                },
                "total_return_pct": {
                    "type": "number"
                },
                "total_trades": {
                    "type": "integer"
                },
                "win_rate_pct": {
                    "type": "number"
                }
            }
        },
        "handler.PortfolioSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.PortfolioResp"
                },
                "message": {
                    "type": "string",
                    "example": "Portfolio retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.PositionResp": {
            "type": "object",
            "properties": {
                "avg_price": {
                    "type": "number"
                },
                "current_price": {
                    "type": "number"
                },
                "entry_time": {
                    "type": "string"
                },
                "market_value": {
                    "type": "number"
                },
                "qty": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "unrealized_pnl": {
                    "type": "number"
                }
            }
        },
        "handler.PositionsSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.PositionResp"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Positions retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.RiskConfigDTO": {
            "type": "object",
            "properties": {
                "daily_loss_limit_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "max_drawdown_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "max_position_pct": {
                    "type": "number",
                    "maximum": 1
                },
                "max_positions": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "handler.StrategyConfigDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        },
        "handler.TradeResp": {
            "type": "object",
            "properties": {
                "entry_price": {
                    "type": "number"
                },
                "entry_time": {
                    "type": "string"
                },
                "exit_price": {
                    "type": "number"
                },
                "exit_time": {
                    "type": "string"
                },
                "pnl": {
                    "type": "number"
                },
                "pnl_pct": {
                    "type": "number"
                },
                "qty": {
                    "type": "number"
                },
                "side": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "handler.TradesSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.TradeResp"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Trades retrieved successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "handler.UpdateBotReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "risk": {
                    "$ref": "#/definitions/handler.BotRiskConfigDTO"
                },
                "strategy": {
                    "$ref": "#/definitions/handler.StrategyConfigDTO"
                },
                "symbols": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.UpdateOrchestratorReq": {
            "type": "object",
            "properties": {
                "capital": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "risk": {
                    "$ref": "#/definitions/handler.RiskConfigDTO"
                }
            }
        },
        "internal_module_orchesrator_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "not found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "internal_module_worker_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "not found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Orchestrator Service API",
	Description:      "Orchestrator service APIs for orchestrators, bots, and signal engine control.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
